# Generated by Django 5.2.6 on 2025-09-22 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudIQApi', '0003_otptable'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='adhaar_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='otptable',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 22, 12, 45, 10, 822923, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
