# Generated by Django 5.2.6 on 2025-09-23 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudIQApi', '0004_customuser_adhaar_no_otptable_expired_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='from_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='from_state',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='to_city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='to_state',
        ),
        migrations.AlterField(
            model_name='otptable',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 23, 6, 55, 4, 828697, tzinfo=datetime.timezone.utc)),
        ),
    ]
