# Generated by Django 5.2.6 on 2025-09-24 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudIQApi', '0006_service_alter_otptable_expired_at_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='description',
            new_name='feature_description',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='service',
            new_name='service_name',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='service_description',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='service_name',
        ),
        migrations.AlterField(
            model_name='otptable',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 24, 11, 57, 51, 153250, tzinfo=datetime.timezone.utc)),
        ),
    ]
