# Generated by Django 5.2.6 on 2025-09-24 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudIQApi', '0007_rename_description_feature_feature_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptable',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 24, 12, 10, 21, 125716, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
