# Generated by Django 5.2.6 on 2025-09-25 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudIQApi', '0009_service_alter_otptable_expired_at_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptable',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 25, 7, 16, 29, 331306, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
