# Generated by Django 5.2.6 on 2025-09-25 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudIQApi', '0010_alter_otptable_expired_at_delete_feature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='otptable',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 25, 7, 31, 26, 73167, tzinfo=datetime.timezone.utc)),
        ),
    ]
