# Generated by Django 5.2.6 on 2025-09-25 09:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudIQApi', '0011_service_alter_otptable_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptable',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 25, 9, 7, 10, 916568, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('feature_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='StudIQApi.service')),
            ],
        ),
    ]
