# Generated by Django 5.2.6 on 2025-10-10 07:57

import cloudinary.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudIQApi', '0015_alter_otptable_expired_at_hostelfacility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptable',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 10, 8, 2, 2, 367406, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='HostelPhoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', cloudinary.models.CloudinaryField(max_length=255)),
                ('is_banner', models.BooleanField(default=False)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='StudIQApi.hostel')),
            ],
        ),
    ]
