# Generated by Django 5.2.6 on 2025-10-14 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudIQApi', '0019_hostel_user_alter_otptable_expired_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otp',
        ),
        migrations.AlterField(
            model_name='otptable',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 14, 8, 20, 4, 421463, tzinfo=datetime.timezone.utc)),
        ),
    ]
